---

sidebar: sidebar
permalink: databases/automation_ora_bkup_clone.html
keywords: Oracle, GCP, GCNV, Database, clone
summary: "The solution provides an Ansible-based automation toolkit for setting up, cloning, and refreshing Oracle clone databases from an Oracle database image backup copy residing in NetApp cloud volumes, which are available from a public cloud platform. The toolkit initially supports the Google Cloud NetApp Volumes (GCNV) but may be expanded to support other cloud volumes such as Azure NetApp Files (ANF) or Amazon FSx for ONTAP (FSxN)." 

---

= Automated Oracle VLDB Clone Lifecycle with In-server image backup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

Allen Cao, Niyaz Mohamed, NetApp

[.lead]
The solution provides an Ansible-based automation toolkit for setting up, cloning, and refreshing Oracle clone databases from an Oracle database image backup copy residing in NetApp cloud volumes, which are available from a public cloud platform. The toolkit initially supports the Google Cloud NetApp Volumes (GCNV) but may be expanded to support other cloud volumes such as Azure NetApp Files (ANF) or Amazon FSx for ONTAP (FSxN).

== Purpose

Leveraging the quick clone (minutes) feature of NetApp ONTAP volumes for Oracle VLDB from an in-server database image backup copy in the public cloud serves multiple purposes. It provides a close to real-time full-size production database for reporting or development or UAT purposes. It saves on storage costs particularly when the thin clone of primary data volumes is an option. This Ansible-based automation toolkit empowers users to set up, clone, and refresh cloned Oracle databases on user-desired schedules for streamlined lifecycle management. The toolkit applies to Oracle databases deployed to the Google public cloud using Google Cloud NetApp Volumes (GCNV) storage for in-server image copy backup for quick database restore and recovery in the event of a primary storage failure.  

This solution addresses the following use cases:

* Setup database clone configuration files for automated Oracle database clone.
* Create or refresh clone Oracle database from a primary database image backup copy using Ansible playbook on a scheduler.

== Audience

This solution is intended for the following people:

* A DBA who manages Oracle databases in Google cloud.
* A storage administrator who manages Google NetApp Volumes storage.
* An application owner who likes to clone Oracle databases from a database image backup copy for other use cases.

== License

By accessing, downloading, installing or using the content in this GitHub repository, you agree the terms of the License laid out in link:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT[License file^].

[NOTE] 

There are certain restrictions around producing and/or sharing any derivative works with the content in this GitHub repository. Please make sure you read the terms of the License before using the content. If you do not agree to all of the terms, do not access, download or use the content in this repository.

== Solution deployment

=== Prerequisites for deployment
[%collapsible%open]
====
Deployment requires the following prerequisites.

  Ansible controller:
    Ansible v.2.10 and higher
    ONTAP collection 21.19.1
    Python 3
    Python libraries:
      netapp-lib
      xmltodict
      jmespath

  Oracle servers:
    Primary Oracle VLDB server with an in-server image backup 
    Clone target Oracle server 
    
[NOTE] 
    For simplification, the clone target Oracle server should be configured identically to the primary Oracle server such as Oracle software stack as well as directory layout for Oracle Home etc.

====

=== Download the toolkit
[%collapsible%open]
====

[source, cli]
https://bitbucket.ngage.netapp.com/projects/NS-BB/repos/na_oracle_bkup_clone/browse

[NOTE]

The toolkit can only be accessed by NetApp internal user with bitbucket access at this moment. For interested external users, please request access from your account team or reach out to NetApp Solutions Engineering team.

====

=== Ansible source and target hosts file configuration
[%collapsible%open]

====

The toolkit includes a hosts file which define the source and targets Oracle hosts that the Ansible playbook running against. Usually, it includes the standby DB host in Data Guard setup and the target Oracle clone host. Following is an example file. A host entry includes target host IP address as well as ssh key for user access to the host to execute clone or refresh command. The Google Cloud NetApp Volumes storage is accessed and managed via gcloud cli. 

 #Oracle hosts
 [ora_prod]
 orap ansible_host=35.212.10.122 ansible_ssh_private_key_file=oras.pem

 [ora_clone]
 orac ansible_host=35.212.1.75 ansible_ssh_private_key_file=orac.pem

 [gcp]
 localhost ansible_connection=local


====
=== Global variables configuration
[%collapsible%open]

====
Below is an example of typical global variable file vars.yml which includes variables that are applicable at the global level. 

 ######################################################################
 ###### Oracle DB clone on GCNV user configuration variables     ######
 ###### Consolidate all variables from GCNV, linux and oracle    ######
 ######################################################################

 ############################################
 ### ONTAP/GCNV specific config variables ###
 ############################################

 # GCNV credential
 key_file: /home/admin/google-cloud-sdk/service_key.json

 # Cloned DB volumes from the primary DB
 project_id: cvs-pm-host-1p
 location: us-east4
 protocol: nfsv3
 bkup_mnt: /nfsgcnv
 ora_data: '{{ bkup_mnt }}/oracopy'
 ora_logs: '{{ bkup_mnt }}/archlog'
 data_vols:
   - "{{ groups.ora_prod[0] }}-bkup"

 nfs_lifs:
   - 10.165.128.5

 nfs_client: 0.0.0.0/0

 ###########################################
 ### Linux env specific config variables ###
 ###########################################


 ####################################################
 ### DB env specific install and config variables ###
 ####################################################

 # Primary DB configuration
 oracle_user: oracle
 oracle_base: /u01/app/oracle
 oracle_sid: NTAP
 oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
 adump: '{{ oracle_base }}/admin/{{ oracle_sid }}/adump'
 db_id: 1379265854

 # Clond DB configuration
 clone_sid: NTAPDEV
 sys_pwd: "XXXXXXXX"


[NOTE]

For a more secure automation deployment, Ansible vault can be employed to encrypt sensitive information such as password, access token or key etc. The solution does not cover Ansible vault implementation but it's well documented in Ansible documentation. Please referred to link:https://docs.ansible.com/ansible/latest/vault_guide/index.html[Protecting sensitive data with Ansible vault^] for details.

====

=== Host variables configuration
[%collapsible%open]
====

Host variables are defined in host_vars directory named as {{ host_name }}.yml that applies to the particular host only. For this solution, only target clone DB host parameter file is configured. Oracle primary DB parameters are configured in global vars file. Below is an example of target Oracle clone DB host variable file orac.yml that shows typical configuration.

 # User configurable Oracle clone host specific parameters

 # Database SID - clone DB SID
 oracle_base: /u01/app/oracle
 oracle_user: oracle
 clone_sid: NTAPDEV
 oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
 clone_adump: '{{ oracle_base }}/admin/{{ clone_sid }}/adump'
 sga_size: 4096M

====

=== Additional clone target Oracle server configuration
[%collapsible%open]
====

Clone target Oracle server should have the same Oracle software stack as source Oracle server installed and patched. $ORACLE_HOME variable should match with source Oracle server setting. If target ORACLE_HOME setting is different from the primary Oracle server configuration, create a symbolic link to work around the differences. 

If the primary database is configured with ASM, the data files primary group may belong to asm group and the same asm group with same group ID should be added to clone host to avoid permission issue.    

====

=== Playbook execution 
[%collapsible%open]
====

There are total of two playbooks to execute Oracle database clone lifecycle. DB clone or refresh can be executed on-demand or scheduled as a crontab job.

. Install Ansible controller prerequisites - one time only.
+
[source,  cli]
ansible-playbook -i hosts ansible_requirements.yml
  
. Create and refresh clone database on-demand or regularly from crontab with a shell script to call the clone or refresh playbook.
+
[source, cli]
ansible-playbook -i hosts oracle_bkup_clone_gcnv.yml -u admin -e @vars/vars.yml
+
[source, cli]
30 */4 * * * /home/admin/na_oracle_bkup_clone/oracle_bkup_clone_gcnv.sh

To clone any additional databases, create a separate oracle_bkup_clone_n_gcnv.yml and oracle_bkup_clone_n_gcnv.sh. Configure the Ansible target hosts, global vars.yml, and hostname.yml file in host_vars directory accordingly.

[NOTE]

The execution of toolkit at various stages pauses to allow a particular task to complete. For example, it pauses for two minutes to allow DB volumes clone to complete. In general, the default should be sufficient but the timing may need adjustment for unique situation or implementation. 

====

== Where to find additional information

To learn more about the NetApp solution automation, review the following website link:../automation/automation_introduction.html[NetApp Solution Automation^]
